(******************************************************************************)
(*                                                                            *)
(*           The Naqoura Line: The Israel-Lebanon Maritime Boundary           *)
(*                                                                            *)
(*     A verified geofence over the 2022 Israel-Lebanon maritime boundary: a  *)
(*     sound, total decision procedure placing any seaward position on the    *)
(*     Israeli or Lebanese side, with certified clearance; extractable.       *)
(*                                                                            *)
(*     "A permanent and equitable resolution of their maritime dispute."      *)
(*     - Israel-Lebanon Exchange of Letters, 2022                             *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: June 2, 2026                                                     *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
